#服务端口
server:
  port: 9000

 #服务名称
spring:
  application:
    name: api-gateway

#注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#自定义路由映射
zuul:
  routes:
    order-service: /api-gateway/**
    #忽略整个服务不对外映射
  ignored-patterns: product-service