server:
  port: 8781

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#服务应用名称
spring:
  application:
    name: order-service
# redis 配置
  redis:
    database: 0
    host: 127.0.0.1
    pool: 6379
    timeout: 2000


#自定义负载均衡策略
product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#设置feign的超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 11000
#Feign结合Hystrix 开启feign支持hystrix
  hystrix:
    enabled: true

# 关闭 hystrix 的超时设置
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false

#设置超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
